### ISSUE TITLE
Feature Request: Add ability to record voice hands-free (voice memo)

### ISSUE THREAD

**Issue by aayushdutt** [maxkrieger/voiceliner#31] opened 2021-12-25 22:06 UTC
Thanks for this awesome app! 
I'd love to use this as a voice diary, where you are just taking a walk and talking through your thoughts in your earphones. It could transcribe and organise your voice memos.

**Comment by maxkrieger** [comment] 2021-12-25 23:24
This isn't very well-specified but sounds like a duplicate of #18. Anything more ambitious than that and you're welcome to fork/PR!

**Closed** 2021-12-25 23:24 UTC
Labels: duplicate, enhancement
