### ISSUE TITLE
Drive Backup not working

### ISSUE THREAD

**Issue by tfiers** [maxkrieger/voiceliner#22] opened 2021-12-14 04:38 UTC
The sign in modal seems to work, but then the spinner just keeps going, "Contacting Drive". Might be related to #8 ?

Android.
![Screenshot_20211214-043640__01.jpg](https://user-images.githubusercontent.com/3773558/145934125-aeb29db3-430f-46a8-9ae2-d7852aae2ea3.jpg)

**Comment by maxkrieger** [comment] 2021-12-25 23:25
Duplicate of #8

**Closed by maxkrieger** 2021-12-25 23:25 UTC
Labels: bug, duplicate, help wanted
