### ISSUE TITLE
FR: Widget for quick record

### ISSUE THREAD

**Issue by shvchk** [maxkrieger/voiceliner#103] opened 2023-07-15 18:10 UTC
Similar to voice recorder apps, would be nice to have a widget to instantly create a memo.

It could work the same as in the app: tap to start record, second tap to stop; or hold to record. Quick memos would probably end up in Inbox, but that could be configurable.

Example with ASR recorder (`com.nll.asr`), cropped video:

https://github.com/maxkrieger/voiceliner/assets/872945/85a9df9a-d12a-4d49-bf64-cb477ee092da

**Comment by shvchk** [comment] 2023-07-15 18:31
Not sure if this should be a separate FR, but it would be also nice to have an [app shortcut](https://developer.android.com/develop/ui/views/launch/shortcuts) of the same purpose, see screenshot below. Thing is, launchers let these shortcuts to be dragged to the home screen as a separate icon, so user can run this shortcut in one tap.

Screenshot of [Audio recorder](https://github.com/Dimowner/AudioRecorder) (open source):

![Screenshot_20230715-212532_Nova7](https://github.com/maxkrieger/voiceliner/assets/872945/888e1865-1b98-4a6b-a776-34d5e84295ad)

**Comment by maxkrieger** [comment] 2023-09-25 17:58
duplicate of #57

**Closed by maxkrieger** 2023-09-25 17:58 UTC
