### ISSUE TITLE
Google Backup

### ISSUE THREAD

**Issue by rahul84206** [maxkrieger/voiceliner#47] opened 2022-01-03 15:17 UTC
![Screenshot_20220103-205843](https://user-images.githubusercontent.com/90828823/147948847-38695ffb-ac72-428d-a59f-dd7f9dff93af.png)
Google backup is not working. While signing for backup with Google, it's showing "couldn't sign in".

Try to resolve this issue.

**Comment by maxkrieger** [comment] 2022-01-03 21:23
Duplicate of #22

**Closed by maxkrieger** 2022-01-03 21:23 UTC
