### ISSUE TITLE
Support for more languages for iOS version

### ISSUE THREAD

**Issue by unkn0w** [maxkrieger/voiceliner#38] opened 2021-12-30 12:37 UTC
iOS version of the app uses native transcription.
This native service supports many languages - not only English.

My suggestion:
App should change transcription language to the same language that system is running.
I have POLISH 🇵🇱 language set on my phone, and I would like to dictate notes in the same language.

This is technically doable, so maybe someone can implement this? :)

**Comment by frafra** [comment] 2021-12-30 14:09
Same with Android I would say.

**Comment by maxkrieger** [comment] 2021-12-30 17:47
Duplicate of #17

**Closed by maxkrieger** 2021-12-30 17:47 UTC
